--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TATCHAN0825/blackjack
build-by-default: true
branches:
- master
projects:
  blackjack:
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: 1.0.0
      - src: PJZ9n/MoneyConnector/MoneyConnector
        version: 2.3.2
...
