---
name: blackjack
version: 1.0.0
main: tatchan\blackjack\Main
api:
  - 3.0.0
  - 4.0.0
load: POSTWORLD
description: BLACKJACKをサーバーでプレイできるようにする
website: https://github.com/TATCHAN0825/blackjack
virions:
  - pmforms
  - MoneyConnector
...
